/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KryptandRegisterContainer {
        "theme": 'light' | 'dark';
    }
    interface RegisterForm {
    }
}
declare global {
    interface HTMLKryptandRegisterContainerElement extends Components.KryptandRegisterContainer, HTMLStencilElement {
    }
    var HTMLKryptandRegisterContainerElement: {
        prototype: HTMLKryptandRegisterContainerElement;
        new (): HTMLKryptandRegisterContainerElement;
    };
    interface HTMLRegisterFormElement extends Components.RegisterForm, HTMLStencilElement {
    }
    var HTMLRegisterFormElement: {
        prototype: HTMLRegisterFormElement;
        new (): HTMLRegisterFormElement;
    };
    interface HTMLElementTagNameMap {
        "kryptand-register-container": HTMLKryptandRegisterContainerElement;
        "register-form": HTMLRegisterFormElement;
    }
}
declare namespace LocalJSX {
    interface KryptandRegisterContainer {
        "theme"?: 'light' | 'dark';
    }
    interface RegisterForm {
        "onFormSubmit"?: (event: CustomEvent<{ email: string; password: string }>) => void;
    }
    interface IntrinsicElements {
        "kryptand-register-container": KryptandRegisterContainer;
        "register-form": RegisterForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kryptand-register-container": LocalJSX.KryptandRegisterContainer & JSXBase.HTMLAttributes<HTMLKryptandRegisterContainerElement>;
            "register-form": LocalJSX.RegisterForm & JSXBase.HTMLAttributes<HTMLRegisterFormElement>;
        }
    }
}
