/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KryptandLoginContainer {
        "theme": 'light' | 'dark';
    }
    interface KryptandLoginForm {
    }
}
declare global {
    interface HTMLKryptandLoginContainerElement extends Components.KryptandLoginContainer, HTMLStencilElement {
    }
    var HTMLKryptandLoginContainerElement: {
        prototype: HTMLKryptandLoginContainerElement;
        new (): HTMLKryptandLoginContainerElement;
    };
    interface HTMLKryptandLoginFormElement extends Components.KryptandLoginForm, HTMLStencilElement {
    }
    var HTMLKryptandLoginFormElement: {
        prototype: HTMLKryptandLoginFormElement;
        new (): HTMLKryptandLoginFormElement;
    };
    interface HTMLElementTagNameMap {
        "kryptand-login-container": HTMLKryptandLoginContainerElement;
        "kryptand-login-form": HTMLKryptandLoginFormElement;
    }
}
declare namespace LocalJSX {
    interface KryptandLoginContainer {
        "theme"?: 'light' | 'dark';
    }
    interface KryptandLoginForm {
        "onFormSubmit"?: (event: CustomEvent<{ email: string; password: string }>) => void;
    }
    interface IntrinsicElements {
        "kryptand-login-container": KryptandLoginContainer;
        "kryptand-login-form": KryptandLoginForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kryptand-login-container": LocalJSX.KryptandLoginContainer & JSXBase.HTMLAttributes<HTMLKryptandLoginContainerElement>;
            "kryptand-login-form": LocalJSX.KryptandLoginForm & JSXBase.HTMLAttributes<HTMLKryptandLoginFormElement>;
        }
    }
}
